config/routes.rb
Applicant2::Application.routes.draw do
  

  get "sessions/new" => "sessions#new", :as => 'log_in'
  get "sessions/destroy" => "sessions#destroy", :as => 'log_out'
  
  get 'applicant_created/:id' => 'applicants#applicant_created', :as => 'applicant_created' 
  get 'confirm/:confirmation_token' => 'users#confirm', :as => 'confirmation' 
  get 'profile/' => 'users#profile', :as => 'profile'
  delete 'profile/portrait' => 'users#delete_portrait', :as => 'remove_portrait'
  delete 'rmfile/:att_type' => 'records#delete_attachment', :as => 'remove_attachment'
  
  get "admin/index" => "admin#index", :as => 'admin'
  get "admin/show_department/:id" => "admin#show_department", :as => "admin_show_department"
  get "admin/show_user/:id" => "admin#show_user", :as => "admin_show_user"
  put "admin/accept_user/:id" => "admin#accept_user", :as => "admin_accept_user"
  put "admin/reject_user/:id" => "admin#reject_user", :as => "admin_reject_user"
  put "admin/notify_complete/:id" => "admin#notify_complete", :as => 'admin_notify_complete_user'
  delete "admin/destroy_user/:id" => "admin#destroy_user", :as => "admin_destroy_user"
  get "admin/export_accepted" => "admin#export_accepted", :as => "accepted_as_csv"
  get "admin/export_rejected" => "admin#export_rejected", :as => "rejected_as_csv"
  
  resources :users do
    resource :record
  end

  namespace :admin do
    resources :users
  end
  
  resources :sessions
  
  root :to => "applicants#index"
  

end

app/views/admin/_admin_links.html.erb
<div class="admin_links">
	<%= link_to("index", admin_path ) %> 
	<% if @user %>
	  &nbsp; | &nbsp;  <%= link_to(@user.department.name, admin_show_department_path(@user.department))%>
	<% end %>
</div>

app/views/admin/index.html.erb
<div class="page-header">
	<h1>Welcome Admin</h1>
</div>

<div class='row-fluid'>
  
  <div class='span6'>
    <div class='well well-large'>
      <p class="lead">
        Es gibt derzeit <%= User.where(:role_id => Role.find_by_name('applicant')).count %> Bewerbungen.
      </p>
	    <p>
	    <ul>
	    <% Department.all.each do |dept| %>
		    <li><%= dept.users.count %> in <%= link_to dept.name, admin_show_department_path(dept.id) %></li>
	    <% end %>
	    </ul>
	    </p>
    </div>
  </div>

  <div class='span6'>
    <div class='well well-large'>
      <%= link_to 'AdministratorInnen', admin_users_path, class: 'btn btn-primary' %>
    </div>
  </div>

</div>

<div class="well well-large">
	
		<p class="lead">Export</p>
		<%= button_to "Angenommene BewerberInnen als CSV-Datei/Excel", accepted_as_csv_path, :method => :get, :class => "btn btn-info btn-large" %> 
		<%= button_to "Abgelehnte BewerberInnen als CSV-Datei/Excel", rejected_as_csv_path, :method => :get, :class => "btn btn-inverse btn-large" %>
	
</div>

app/views/admin/show_department.html.erb
<div class="page-header">
	<h1><%= @department.name %></h1>
</div>

<div class="well well-large">
	<div class="span6">
		<%= render('admin_links') %>
	</div>
	<div class="span6">
		<p>
			Es gibt in diesem Department <%= @department.users.count %> Bewerbungen.
			( <%= @department.users.where("accepted=?", true).count %> angenommen,
			<%= @department.users.where("accepted=?", false).count %> abgelehnt und
			<%= @department.users.where("accepted IS ?", nil ).count %> noch nicht beschieden. )
		</p>
	</div>
</div>

<table class="table table-striped">
	<tr>
		<th>Image</th>
		<th>Name</th>
		<th>Email</th>
		<th>vom</th>
		<th>bestätigt?</th>
		<th>status</th>
		<th>Aktion</th>
	</tr>
	<% @department.users.each do |user| %>
	<tr>
		<td><%= image_tag user.portrait.url(:thumb) %></td>
		<td><%= user.name %></td>
		<td><%= user.email %></td>
		<td><%= user.created_at.strftime("%d.%m.%y")%></td>
		<td><%= user.confirmed_at ? "ja" : "noch nicht" %></td>
		<td><%= user.record_complete? ? "vollständig" : "unvollständig" %> | <%= show_decision_status(user) %></td>
		<td><%= link_to('ansehen', admin_show_user_path(user), class: 'btn btn-primary' ) %></td>
	</tr>
	<% end %>
</table>

app/views/admin/show_user.html.erb
<div class="well well-large">
	<div class="span6">
		<%= render('admin_links') %>
	</div>
	<div class="span6">
		<% if @user.decision_made? %>
		<p class="lead">
			BewerberIn <span class="label <%= @user.accepted? ? 'label-success' : 'label-important' %>"><%= @user.accepted? ? 'angenommen' : 'abgelehnt' %>!</span>
		</p>
		<% else %>
		<p class="label label-warning">
			Entscheidung über Annahme steht noch aus - siehe unten
		</p>
		<% end %>
	</div>
</div>

<section class="clearfix">
	<div class="span6">
		<div id="portrait">
			<%= image_tag @user.portrait.url(:normal), :class => "img-polaroid" %>
		</div>
		<h1><%= @user.name %></h1>
		<p>Registriert am: <%= @user.created_at.strftime("%d.%m.%y") %></p>
		<p>Basisdaten</p>
		<ul>
			<li><%= @user.email%></li>
			<li><%= @user.phone %></li>
			<li><%= @user.date_of_birth.strftime("%d.%m.%Y")%></li>
		</ul>
	</div>
	
	<div class="span6">
	<p>Die Bewerbung scheint <%= @user.record_complete? ? "vollständig" : "unvollständig" %> zu sein.</p>
  
	<p>
		<% missing = missing_records_for(@user) %>
		<% unless missing.empty? %>
		<strong>Zu dieser Bewerbung fehlt potentiell noch: </strong>
		<ul>
			<% missing.each do |m| %>
				<li><%= m %></li>
			<% end %>
		</ul>
		<% end %>
	</p>

	<% if @user.record && @user.record.attachments? %>
		<p><strong>Zur Bewerbung wurde hochgeladen: </strong>
		<ul>
			<% if @user.record.primary? %>
				<li>Bewerbungsbogen: <%= truncate(name_for_attachment(@user.record.primary)) %> <%= link_to('download', @user.record.primary.url ) %></li>
			<% end %>
			<% if @user.record.common_task? %>
				<li>Allgemeiner Teil: <%= truncate(name_for_attachment(@user.record.common_task)) %> <%= link_to('download', @user.record.common_task.url) %></li>
			<% end %>
			<% if @user.record.specific_task? %>
				<li>Fachspezifischer Teil: <%= truncate(name_for_attachment(@user.record.specific_task)) %> <%= link_to('download', @user.record.specific_task.url ) %></li>
			<% end %>
			<% if @user.record.image_archive? %>
				<li>ggfls. Fotoreihe: <%= truncate(name_for_attachment(@user.record.image_archive)) %> <%= link_to('download', @user.record.image_archive.url ) %></li>
			<% end %>
		</ul>
		</p>
	<% end %>
	<p><strong>Bewerbungsfilm:</strong>
    <br />
    <%= link_to @user.record.video_url, @user.record.video_url %> password: <%= @user.record.video_password %>
    <% if @user.department.name == 'Regie' %>
      <%= link_to @user.record.video2_url, @user.record.video2_url %> 
    <% end %>
	</p>
	<p><strong>Kommentar des Bewerbers:</strong></p>
	<p><%= h @user.record.comment %></p>
	</div>
</section>

<div class="form-actions">
  
	<% if @user.decision_made? %>
		<p>Bewerber_in angenommen: <%= @user.accepted? %></p>
		<%= link_to(admin_accept_user_path(:id => @user), :data => { :confirm => "Den/die BewerberIn annehmen?" }, :method => :put, :class => "btn btn-success") do %>
      <i class='icon-thumbs-up icon-white'> </i> BewerberIn annehmen
    <% end unless @user.accepted? %>
    <%= link_to(admin_reject_user_path(:id => @user), :data => { :confirm => "den/die BewerberIn ablehnen?" }, :method => :put, :class => "btn btn-inverse") do  %>
      
      <i class='icon-thumbs-down icon-white'> </i> BewerberIn ablehnen
    <% end if @user.accepted? %>
	<% else %>
    <p>Entscheidung steht noch aus!</p>
    <% if @user.record_complete? %>
      <%= link_to 'Versende einen Vollständigkeits-Hinweis', 
        admin_notify_complete_user_path(@user), method: :put, class: 'btn btn-warning' %>
      <% unless @user.notified_complete %>
        <p class='help-text'>Noch nicht über Vollständigkeit benachrichtigt.</p>
      <% end %>
    <% end %>
    
    <% if @user.record_complete? %>
      <%= link_to( admin_accept_user_path(:id => @user), :data => { :confirm => "Den/die BewerberIn annehmen?" }, :method => :put, :class => "btn btn-success" ) do %>
        <i class='icon-thumbs-up icon-white'> </i> BewerberIn annehmen
      <% end %>
    <% else %>
      <p class='text text-warning'>Bewerbung unvollständig - noch nicht annahmefähig.</p>
    <% end %>
    <%= link_to( admin_reject_user_path(:id => @user), :data => { :confirm => "Den/die BewerberIn ablehnen?" }, :method => :put, :class => "btn btn-inverse") do %>
      <i class='icon-thumbs-down icon-white'> </i> BewerberIn ablehnen
    <% end %>
	<% end %>
	<%= link_to("BewerberIn löschen", admin_destroy_user_path(:id => @user), :data => { :confirm => "Den/die BewerberIn löschen?"}, :method => :delete, :class => "btn btn-danger pull-right" )%>
</div>