config/routes.rb
Applicant2::Application.routes.draw do
  

  get "sessions/new" => "sessions#new", :as => 'log_in'
  get "sessions/destroy" => "sessions#destroy", :as => 'log_out'
  
  get 'applicant_created/:id' => 'applicants#applicant_created', :as => 'applicant_created' 
  get 'confirm/:confirmation_token' => 'users#confirm', :as => 'confirmation' 
  get 'profile/' => 'users#profile', :as => 'profile'
  delete 'profile/portrait' => 'users#delete_portrait', :as => 'remove_portrait'
  delete 'rmfile/:att_type' => 'records#delete_attachment', :as => 'remove_attachment'
  
  get "admin/index" => "admin#index", :as => 'admin'
  get "admin/show_department/:id" => "admin#show_department", :as => "admin_show_department"
  get "admin/show_user/:id" => "admin#show_user", :as => "admin_show_user"
  put "admin/accept_user/:id" => "admin#accept_user", :as => "admin_accept_user"
  put "admin/reject_user/:id" => "admin#reject_user", :as => "admin_reject_user"
  put "admin/notify_complete/:id" => "admin#notify_complete", :as => 'admin_notify_complete_user'
  delete "admin/destroy_user/:id" => "admin#destroy_user", :as => "admin_destroy_user"
  get "admin/export_accepted" => "admin#export_accepted", :as => "accepted_as_csv"
  get "admin/export_rejected" => "admin#export_rejected", :as => "rejected_as_csv"
  
  resources :users do
    resource :record
  end

  namespace :admin do
    resources :users
  end
  
  resources :sessions
  
  root :to => "applicants#index"
  

end

app/models/user.rb
require 'digest'
require 'csv'

class User < ActiveRecord::Base

  attr_accessor :password
 
  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :firstname, :lastname, :phone, :department_id, :date_of_birth, :department, :password_confirmation, :portrait, :confirmed_at
  
  belongs_to :department
  has_one :record, :dependent => :destroy
  belongs_to :role
  has_attached_file :portrait, :styles => { :thumb => ["60x60", :jpg], :normal => ["200x200", :jpg] }, :dependent => :destroy
  
  validates_confirmation_of :password
  
  validates :email, :uniqueness => true
  validates :firstname, :lastname, :email, presence: true
  validates :phone, :date_of_birth, :department, :presence => true,  :unless => Proc.new { |user| user.role.name == 'admin' }
  validate :validate_minimum_age
  
  before_save :encrypt_password
  before_create :create_confirmation_token
  
  scope :admins, -> { joins(:role).where('roles.name=?', 'admin') }

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt) &&! user.confirmed_at.nil?
      user
    end
  end
  
  def name
    "#{firstname} #{lastname}"
  end
  
  def record_complete?
    self.record && self.record.complete?
  end
  
  def accepted?
    accepted ? true : false
  end
  
  def decision_made?
    accepted.nil? ? false : true
  end

  def fullname
    "#{firstname} #{lastname}"
  end
  
  private
  
  def create_confirmation_token
    self.confirmation_token = Digest::SHA2.new.hexdigest("foobar-#{rand(10000)}" << Time.now.to_s)
    #update_attribute(:confirmation_token, Digest::SHA2.new.hexdigest("foobar-" << Time.now.to_s))
  end
  
  def encrypt_password
    if self.password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
  
  def validate_minimum_age
    bd = date_of_birth
    min = Date.parse("1.10.#{Date.today.year-21}")
    begin
      if date_of_birth > min
        errors.add(:date_of_birth, "Mindestalter ist 21 Jahre")
      end
    rescue
      errors.add(:date_of_birth, "bitte in der form: 01.04.1900")
    end
  end
  
  def self.to_csv(users)
    csv_data = CSV.generate do |csv|
      csv << %w(id department lastname firstname email phone image)
      users.each do |user|
        csv << [user.id, user.department.name, user.lastname, user.firstname, user.email, user.phone, "http://bewerbung.filmarche.de#{user.portrait.url(:normal)}" ]
      end
    end
    return csv_data
  end
  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  
  layout 'applicant'

  before_filter :restrict_admin_access

  # GET /admin/users
  # GET /admin/users.json
  def index
    @admin_users = User.admins

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @admin_users }
    end
  end

  # GET /admin/users/1
  # GET /admin/users/1.json
  def show
    @admin_user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @admin_user }
    end
  end

  # GET /admin/users/new
  # GET /admin/users/new.json
  def new
    @admin_user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @admin_user }
    end
  end

  # GET /admin/users/1/edit
  def edit
    @admin_user = User.find(params[:id])
  end

  # POST /admin/users
  # POST /admin/users.json
  def create
    @admin_user = User.new(params[:user])
    @admin_user.role = Role.find_by_name('admin')
    @admin_user.date_of_birth = Date.parse('18.10.1977')
    @admin_user.confirmed_at = Date.today

    respond_to do |format|
      if @admin_user.save
        format.html { redirect_to admin_users_path, notice: 'User was successfully created.' }
        format.json { render json: @admin_user, status: :created, location: @admin_user }
      else
        format.html { render action: "new" }
        format.json { render json: @admin_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/users/1
  # PUT /admin/users/1.json
  def update
    @admin_user = User.find(params[:id])

    respond_to do |format|
      if @admin_user.update_attributes(params[:user])
        format.html { redirect_to admin_users_path, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @admin_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/users/1
  # DELETE /admin/users/1.json
  def destroy
    @admin_user = User.find(params[:id])
    @admin_user.destroy

    respond_to do |format|
      format.html { redirect_to admin_users_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'applicant'
  #before_filter :authenticate_user!
  
  # GET /users
  # GET /users.json
  #def index
  #  @users = User.all

  #  respond_to do |format|
  #    format.html # index.html.erb
  #    format.json { render json: @users }
  #  end
  #end
  
  def profile
    @user = current_user || User.new
    @record = @user.record || @user.build_record
  end
  

  # GET /users/1
  # GET /users/1.json
  #def show
  #  @user = User.find(params[:id])#

  #  respond_to do |format|
  #    format.html # show.html.erb
  #    format.json { render json: @user }
  #  end
  #end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  #def edit
  #  @user = User.find(params[:id])
  #end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      _role  = Role.find_by_name('applicant')
      @user.role = _role
      if @user.save
        @user.reload
        n = Notifications.confirmation(@user)
        logger.debug("Users#create - Notification: #{n.inspect}")
        n.deliver
        format.html { redirect_to applicant_created_path(:id => @user.id), notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html do
          flash[:alert] = "Es sind Fehler aufgetreten, bitte sieh dir das Formular an und beachte die Hinweise!"
          render :action => 'new'
         end
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = current_user #User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to profile_path, notice: 'Daten aktualisiert' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = current_user # User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
  
  def delete_portrait
    @user = current_user
    @user.portrait.destroy
    if @user.save
      flash[:notice] = "Passbild geloescht"
      redirect_to profile_path
    else
      logger.error("Users#delete_portrait - error: #{@user.errors.inspect}")
      flash[:alert] = "Bild konnte nicht entfernt werden"
      redirect_to profile_path
    end
  end
  
  def confirm
    if user = User.find_by_confirmation_token(params[:confirmation_token])
      user.confirmed_at = Time.now
      respond_to do |format|
        if user.save
          logger.info("Applicants#confirm - user_id confirmed: #{user.id}")
          user.update_attribute(:confirmation_token, nil)
          session[:user_id] = user.id
          format.html { redirect_to profile_path, :notice => 'Email-Adresse bestaetigt' }
        else
          format.html {redirect_to root_path, :alert => "Email konnte nicht bestaetigt werden" }
        end
      end
    else
      logger.warn("Applicants#confirm - no such user by confirmation_token: #{params[:confirmation_token]}")
      flash[:alert] = "Kein solcher confirmation-code vorhanden"
      redirect_to root_path
    end
  end
  
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
  
  def delete_links_for_attachments_on(record)
    hash = {}
    if record.primary?
      hash[:primary] = record.primary.path.split("/")[-1]
    end
    
    if record.common_task?
      hash[:common_task] = record.common_task.path.split("/")[-1]
    end
    
    if record.specific_task?
      hash[:specific_task] = record.specific_task.path.split("/")[-1]
    end
    
    if record.image_archive?
      hash[:image_archive] = record.image_archive.path.split("/")[-1]
    end    
    
    ret = ""
    hash.each_pair do |k,v|
      ret << content_tag(:li, truncate(v).concat(" ").concat( link_to('entfernen', remove_attachment_path(:user_id => record.user.id,:method => :delete, :confirm => "Datei loeschen?", :att_type => k)).html_safe) )  
    end
    ret    
  end
  
  def name_for_attachment(ppatt)
    ppatt.path.split("/")[-1]
  end
 
end

app/views/admin/users/_form.html.erb
<%= form_for([:admin,@admin_user]) do |f| %>
  <% if @admin_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_user.errors.count, "error") %> prohibited this admin_user from being saved:</h2>

      <ul>
      <% @admin_user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
	  <%= f.label :vorname, :class => "control-label" %>
	  <div class="controls">
		  <%= f.text_field :firstname, :id => "vorname", :class => "input-xlarge" -%>
  	</div>
  </div>
  <div class="control-group">
	  <%= f.label :name, :class => "control-label" %>
	  <div class="controls">
		  <%= f.text_field :lastname, :id => "name", :class => "input-xlarge" %>
	  </div>
  </div>
  <div class="control-group">
	  <%= f.label :email, :class => "control-label" %>
	  <div class="controls">
		  <%= f.email_field :email, :id => "email", :class => "input-xlarge" %>
	  </div>
  </div>

  <div class="control-group">
	  <%= f.label :password, :class => "control-label" %>
	  <div class="controls">
		  <%= f.password_field :password, :id => "email", :class => "input-xlarge" %>
	  </div>
  </div>
  <div class="control-group">
	  <%= f.label :password_confirmation, :class => "control-label" %>
	  <div class="controls">
		  <%= f.password_field :password_confirmation, :id => "email", :class => "input-xlarge" %>
	  </div>
  </div>
  <div class="actions">
    <%= f.submit nil, class: 'btn btn-primary' %>
    
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<div class='page-header'>
  <h1>Editiere <%= @admin_user.fullname %></h1>
</div>

<%= render 'form' %>

<%= link_to 'Back', admin_users_path %>

app/views/admin/users/index.html.erb
<div class='page-header'>
  <h1>AdministratorInnen</h1>
</div>

<table class='table table-striped table-hover'>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Aktion</th>
  </tr>

<% @admin_users.each do |admin_user| %>
  <tr>
    <td><%= admin_user.fullname %></td>
    <td><%= admin_user.email %></td>
    <td>
      <div class='pull-right'>
      <%= link_to 'Edit', edit_admin_user_path(admin_user) , class: 'btn btn-warning'%>
      <%= link_to 'Destroy', admin_user_path(admin_user), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'%>
    </div>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Admin', new_admin_user_path, class: 'btn btn-primary' %>

app/views/admin/users/new.html.erb
<div class='page-header'>
  <h1>Neue/en AdministratorIn</h1>
</div>

<%= render 'form' %>

<%= link_to 'Back', admin_users_path %>

app/views/admin/users/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_admin_user_path(@admin_user) %> |
<%= link_to 'Back', admin_users_path %>